default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: developer
  host: localhost

development:
  <<: *default
  database: whether-app-dev

test:
  <<: *default
  database: whether-app-test

production:
  <<: *default
  database: whether-app-pro
